//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Player {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResStr1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResStr1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Player.ResStr1", typeof(ResStr1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string BtnLoad {
            get {
                return ResourceManager.GetString("BtnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload.
        /// </summary>
        public static string BtnUnload {
            get {
                return ResourceManager.GetString("BtnUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media file,DirectShow device,URL.
        /// </summary>
        public static string ComboTypes {
            get {
                return ResourceManager.GetString("ComboTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video/audio to play..
        /// </summary>
        public static string Msg1 {
            get {
                return ResourceManager.GetString("Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize ffmpeg..
        /// </summary>
        public static string Msg2 {
            get {
                return ResourceManager.GetString("Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load item..
        /// </summary>
        public static string Msg3 {
            get {
                return ResourceManager.GetString("Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source URL is empty..
        /// </summary>
        public static string Msg4 {
            get {
                return ResourceManager.GetString("Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter command error..
        /// </summary>
        public static string Msg5 {
            get {
                return ResourceManager.GetString("Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save frame..
        /// </summary>
        public static string Msg6 {
            get {
                return ResourceManager.GetString("Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command or argument is not set..
        /// </summary>
        public static string Msg7 {
            get {
                return ResourceManager.GetString("Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player: an async operation is in progress..
        /// </summary>
        public static string Msg8 {
            get {
                return ResourceManager.GetString("Msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player error..
        /// </summary>
        public static string Msg9 {
            get {
                return ResourceManager.GetString("Msg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/unload media source (Ctrl+Enter).
        /// </summary>
        public static string TpBtnLoadUnload {
            get {
                return ResourceManager.GetString("TpBtnLoadUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle mute mode (F7).
        /// </summary>
        public static string TpBtnMute {
            get {
                return ResourceManager.GetString("TpBtnMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the next frame (F12).
        /// </summary>
        public static string TpBtnNextFrame {
            get {
                return ResourceManager.GetString("TpBtnNextFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle source pixel to screen pixel mode (Ctrl+2).
        /// </summary>
        public static string TpBtnPix2Pix {
            get {
                return ResourceManager.GetString("TpBtnPix2Pix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/pause (Ctrl+P).
        /// </summary>
        public static string TpBtnPlayPause {
            get {
                return ResourceManager.GetString("TpBtnPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the previous frame (F11).
        /// </summary>
        public static string TpBtnPrevFrame {
            get {
                return ResourceManager.GetString("TpBtnPrevFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/stop rewinding forward with given frame rate (Ctrl+R).
        /// </summary>
        public static string TpBtnRewind {
            get {
                return ResourceManager.GetString("TpBtnRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current frame in a jpeg/png file (Ctrl+F).
        /// </summary>
        public static string TpBtnSaveFrame {
            get {
                return ResourceManager.GetString("TpBtnSaveFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playing (Ctrl+S).
        /// </summary>
        public static string TpBtnStop {
            get {
                return ResourceManager.GetString("TpBtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame rate for rewinding (Ctrl+U, arrows up/down).
        /// </summary>
        public static string TpComboFramerate {
            get {
                return ResourceManager.GetString("TpComboFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust sound volume (F8 - down, F9 - up).
        /// </summary>
        public static string TpSldVolume {
            get {
                return ResourceManager.GetString("TpSldVolume", resourceCulture);
            }
        }
    }
}
